name: web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: ironman <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  core:
    path: ../core
  angular: ^6.0.0-alpha+1
  angular_router: ^2.0.0-alpha+19
  key_value_store_web: ^1.0.0
  pwa: ^0.2.0

dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.7.4
  build_test: ^0.10.12+1
  build_web_compilers: ^2.9.0
  sass_builder: ^2.1.3
  test: ^1.14.1
